const homePage = require('../pages/home.page')
const productDetailPage = require('../pages/productDetail.page')
const cartPage = require('../pages/cart.page')
const { assert } = require('chai')

describe('Checkout Tests', function() {
    it('should checkout without signing in', () => {
        browser.url('/')
        homePage.clickProduct(1)
        productDetailPage.clickAddToCartButton()
        productDetailPage.clickCart()
        cartPage.clickCheckoutButton()
        browser.switchToFrame(cartPage.iFrame)
        cartPage.enterEmail('desk@desk.com')
        cartPage.enterName('Desk')
        cartPage.enterStreet('123 Desk St.')
        cartPage.enterCity('Deskville')
        cartPage.enterZipCode('12345')
        cartPage.clickPaymentInfoButton()
        cartPage.enterCardNumber('4242 4242 4242 4242')
        cartPage.enterCardExpiration('0125')
        cartPage.enterCVC('123')
        cartPage.clickPayButton()
        assert.equal('Your placed!', cartPage.orderSuccessMessage.getText())
    })
})