const homePage = require('../pages/home.page')
const productDetailPage = require('../pages/productDetail.page')
const cartPage = require('../pages/cart.page')
const { assert } = require('chai')
const loginPage = require('../pages/login.page')
const myaccountPage = require('../pages/myaccount.page')

describe('Checkout Tests', function() {
    it('should checkout without signing in', () => {
        browser.url('/')
        homePage.clickProduct(1)
        productDetailPage.clickAddToCartButton()
        browser.waitUntil(() => {
            return productDetailPage.cart.getText() === 'Cart (1)'
        }, 5000, 'expect cart qty to update')
        productDetailPage.clickCart()
        cartPage.clickCheckoutButton()
        browser.switchToFrame(cartPage.iFrame)
        cartPage.enterEmail('desk@desk.com')
        cartPage.enterName('Desk')
        cartPage.enterStreet('123 Desk St.')
        cartPage.enterCity('Deskville')
        cartPage.enterZipCode('12345')
        cartPage.clickPaymentInfoButton()
        cartPage.enterCardNumber('4242 4242 4242 4242')
        cartPage.enterCardExpiration('0125')
        cartPage.enterCVC('123')
        cartPage.clickPayButton()
        assert.equal('Your placed!', cartPage.orderSuccessMessage.getText())
    })

    it('should checkout with user signed in', () => {
        browser.url('login/')
        loginPage.enterEmail('desk@desk.com')
        loginPage.enterPassword('desk1')
        loginPage.clickLoginButton()
        browser.waitUntil(() => {
            return browser.getUrl() === 'https://qw-test-store-prod.netlify.app/myaccount/'
        }, 5000, 'expect url to change')
        myaccountPage.clickHomePageLink()
        homePage.clickProduct(1)
        productDetailPage.clickAddToCartButton()
        browser.waitUntil(() => {
            return productDetailPage.cart.getText() === 'Cart (1)'
        }, 5000, 'expect cart qty to update')
        productDetailPage.clickCart()
        cartPage.clickCheckoutButton()
        browser.switchToFrame(cartPage.iFrame)
        cartPage.enterEmail('desk@desk.com')
        cartPage.enterName('Desk')
        cartPage.enterStreet('123 Desk St.')
        cartPage.enterCity('Deskville')
        cartPage.enterZipCode('12345')
        cartPage.clickPaymentInfoButton()
        cartPage.enterCardNumber('4242 4242 4242 4242')
        cartPage.enterCardExpiration('0125')
        cartPage.enterCVC('123')
        cartPage.clickPayButton()
        assert.equal('Your placed!', cartPage.orderSuccessMessage.getText())
    })
})